<?php

namespace myfaker;

class MyFaker {
    private static $rules = [
        'randomDigit'=>['desc'=>'Random Digit','args'=>[]],
        'randomDigitNotNull'=>['desc'=>'Random Digit Not Null','args'=>[]],
        'randomNumber'=>['desc'=>'Random Number','args'=>['nbDigits' => NULL, 'strict' => false]],
        'randomFloat'=>['desc'=>'Random Float','args'=>['nbMaxDecimals' => NULL, 'min' => 0, 'max' => NULL]],
        'numberBetween'=>['desc'=>'Number Between','args'=>['min' => 1000, 'max' => 9000]],
        'randomLetter'=>['desc'=>'Random Letter','args'=>[]],
        'randomElements'=>['desc'=>'Random Elements','args'=>['array' => array ('a','b','c'), 'count' => 1]],
        'randomElement'=>['desc'=>'Random Element','args'=>['array' => array ('a','b','c')]],
        'shuffle'=>['desc'=>'Shuffle','args'=>['array'=>[]]],
        'numerify'=>['desc'=>'Numerify','args'=>['string'=>'Hello ###']],
        'lexify'=>['desc'=>'Lexify','args'=>['string'=>'Hello ???']],
        'bothify'=>['desc'=>'Bothify','args'=>['string'=>'Hello ##??']],
        'asciify'=>['desc'=>'Asciify','args'=>['string'=>'Hello ***']],
        'regexify'=>['desc'=>'Regexify','args'=>['string'=>'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}']],
        'word'=>['desc'=>'Word','args'=>[]],
        'words'=>['desc'=>'Words','args'=>['nb' => 3, 'asText' => false]],
        'sentence'=>['desc'=>'Sentence','args'=>['nbWords' => 6, 'variableNbWords' => true]],
        'sentences'=>['desc'=>'Sentences','args'=>['nb' => 3, 'asText' => false]],
        'paragraph'=>['desc'=>'Paragraph','args'=>['nbSentences' => 3, 'variableNbSentences' => true]],
        'paragraphs'=>['desc'=>'Paragraphs','args'=>['nb' => 3, 'asText' => false]],
        'text'=>['desc'=>'Text','args'=>['maxNbChars' => 200]],
        'title'=>['desc'=>'Title','args'=>['gender' => null]],
        'titleMale'=>['desc'=>'Title Male','args'=>[]],
        'titleFemale'=>['desc'=>'Title Female','args'=>[]],
        'suffix'=>['desc'=>'Suffix','args'=>[]],
        'name'=>['desc'=>'Name','args'=>['gender' => null]],
        'firstName'=>['desc'=>'First Name','args'=>['gender' => null]],
        'firstNameMale'=>['desc'=>'First Name Male','args'=>[]],
        'firstNameFemale'=>['desc'=>'First Name Female','args'=>[]],
        'lastName'=>['desc'=>'Last Name','args'=>[]],
        'cityPrefix'=>['desc'=>'City Prefix','args'=>[]],
        'secondaryAddress'=>['desc'=>'Secondary Address','args'=>[]],
        'state'=>['desc'=>'State','args'=>[]],
        'stateAbbr'=>['desc'=>'State Abbr','args'=>[]],
        'citySuffix'=>['desc'=>'City Suffix','args'=>[]],
        'streetSuffix'=>['desc'=>'Street Suffix','args'=>[]],
        'buildingNumber'=>['desc'=>'Building Number','args'=>[]],
        'city'=>['desc'=>'City','args'=>[]],
        'streetName'=>['desc'=>'Street Name','args'=>[]],
        'streetAddress'=>['desc'=>'Street Address','args'=>[]],
        'postcode'=>['desc'=>'Postcode','args'=>[]],
        'address'=>['desc'=>'Address','args'=>[]],
        'country'=>['desc'=>'Country','args'=>[]],
        'latitude'=>['desc'=>'Latitude','args'=>['min' => -90, 'max' => 90]],
        'longitude'=>['desc'=>'Longitude','args'=>['min' => -180, 'max' => 180]],
        'phoneNumber'=>['desc'=>'Phone Number','args'=>[]],
        'tollFreePhoneNumber'=>['desc'=>'Toll Free Phone Number','args'=>[]],
        'e164PhoneNumber'=>['desc'=>'E164 Phone Number','args'=>[]],
        'catchPhrase'=>['desc'=>'Catch Phrase','args'=>[]],
        'bs'=>['desc'=>'Bs','args'=>[]],
        'company'=>['desc'=>'Company','args'=>[]],
        'companySuffix'=>['desc'=>'Company Suffix','args'=>[]],
        'jobTitle'=>['desc'=>'Job Title','args'=>[]],
        'realText'=>['desc'=>'Real Text','args'=>['maxNbChars' => 200, 'indexSize' => 2]],
        'unixTime'=>['desc'=>'Unix Time','args'=>['max' => 'now']],
        'dateTime'=>['desc'=>'Date Time','args'=>['max' => 'now', 'timezone' => null]],
        'dateTimeAD'=>['desc'=>'Date Time A D','args'=>['max' => 'now', 'timezone' => null]],
        'iso8601'=>['desc'=>'Iso8601','args'=>['max' => 'now']],
        'date'=>['desc'=>'Date','args'=>['format' => 'Y-m-d', 'max' => 'now']],
        'time'=>['desc'=>'Time','args'=>['format' => 'H:i:s', 'max' => 'now']],
        'dateTimeBetween'=>['desc'=>'Date Time Between','args'=>['startDate' => '-30 years', 'endDate' => 'now', 'timezone' => null]],
        'dateTimeInInterval'=>['desc'=>'Date Time In Interval','args'=>['startDate' => '-30 years', 'interval' => '+ 5 days', 'timezone' => null]],
        'dateTimeThisCentury'=>['desc'=>'Date Time This Century','args'=>['max' => 'now', 'timezone' => null]],
        'dateTimeThisDecade'=>['desc'=>'Date Time This Decade','args'=>['max' => 'now', 'timezone' => null]],
        'dateTimeThisYear'=>['desc'=>'Date Time This Year','args'=>['max' => 'now', 'timezone' => null]],
        'dateTimeThisMonth'=>['desc'=>'Date Time This Month','args'=>['max' => 'now', 'timezone' => null]],
        'amPm'=>['desc'=>'Am Pm','args'=>['max' => 'now']],
        'dayOfMonth'=>['desc'=>'Day Of Month','args'=>['max' => 'now']],
        'dayOfWeek'=>['desc'=>'Day Of Week','args'=>['max' => 'now']],
        'month'=>['desc'=>'Month','args'=>['max' => 'now']],
        'monthName'=>['desc'=>'Month Name','args'=>['max' => 'now']],
        'year'=>['desc'=>'Year','args'=>['max' => 'now']],
        'century'=>['desc'=>'Century','args'=>[]],
        'timezone'=>['desc'=>'Timezone','args'=>[]],
        'email'=>['desc'=>'Email','args'=>[]],
        'safeEmail'=>['desc'=>'Safe Email','args'=>[]],
        'freeEmail'=>['desc'=>'Free Email','args'=>[]],
        'companyEmail'=>['desc'=>'Company Email','args'=>[]],
        'freeEmailDomain'=>['desc'=>'Free Email Domain','args'=>[]],
        'safeEmailDomain'=>['desc'=>'Safe Email Domain','args'=>[]],
        'userName'=>['desc'=>'User Name','args'=>[]],
        'password'=>['desc'=>'Password','args'=>[]],
        'domainName'=>['desc'=>'Domain Name','args'=>[]],
        'domainWord'=>['desc'=>'Domain Word','args'=>[]],
        'tld'=>['desc'=>'Tld','args'=>[]],
        'url'=>['desc'=>'Url','args'=>[]],
        'slug'=>['desc'=>'Slug','args'=>[]],
        'ipv4'=>['desc'=>'Ipv4','args'=>[]],
        'localIpv4'=>['desc'=>'Local Ipv4','args'=>[]],
        'ipv6'=>['desc'=>'Ipv6','args'=>[]],
        'macAddress'=>['desc'=>'Mac Address','args'=>[]],
        'userAgent'=>['desc'=>'User Agent','args'=>[]],
        'chrome'=>['desc'=>'Chrome','args'=>[]],
        'firefox'=>['desc'=>'Firefox','args'=>[]],
        'safari'=>['desc'=>'Safari','args'=>[]],
        'opera'=>['desc'=>'Opera','args'=>[]],
        'internetExplorer'=>['desc'=>'Internet Explorer','args'=>[]],
        'creditCardType'=>['desc'=>'Credit Card Type','args'=>[]],
        'creditCardNumber'=>['desc'=>'Credit Card Number','args'=>[]],
        'creditCardExpirationDate'=>['desc'=>'Credit Card Expiration Date','args'=>[]],
        'creditCardExpirationDateString'=>['desc'=>'Credit Card Expiration Date String','args'=>[]],
        'creditCardDetails'=>['desc'=>'Credit Card Details','args'=>[]],
        'iban'=>['desc'=>'Iban','args'=>['countryCode']],
        'swiftBicNumber'=>['desc'=>'Swift Bic Number','args'=>[]],
        'hexcolor'=>['desc'=>'Hexcolor','args'=>[]],
        'rgbcolor'=>['desc'=>'Rgbcolor','args'=>[]],
        'rgbColorAsArray'=>['desc'=>'Rgb Color As Array','args'=>[]],
        'rgbCssColor'=>['desc'=>'Rgb Css Color','args'=>[]],
        'safeColorName'=>['desc'=>'Safe Color Name','args'=>[]],
        'colorName'=>['desc'=>'Color Name','args'=>[]],
        'fileExtension'=>['desc'=>'File Extension','args'=>[]],
        'mimeType'=>['desc'=>'Mime Type','args'=>[]],
        /**
        'file'=>['desc'=>'File','args'=>['sourceDir' => '/tmp', 'targetDir' => '/tmp']],
        'file'=>['desc'=>'File','args'=>['sourceDir', 'targetDir', false) ]],
        'imageUrl'=>['desc'=>'Image Url','args'=>['width' => 640, 'height' => 480]],
        'imageUrl'=>['desc'=>'Image Url','args'=>['width', 'height', 'cats']],
        'imageUrl'=>['desc'=>'Image Url','args'=>['width', 'height', 'cats', true, 'Faker']],
        'imageUrl'=>['desc'=>'Image Url','args'=>['width', 'height', 'cats', true, 'Faker', true]],
        'image'=>['desc'=>'Image','args'=>['dir' => '/tmp', 'width' => 640, 'height' => 480]],
        'image'=>['desc'=>'Image','args'=>['dir', 'width', 'height', 'cats']],
        'image'=>['desc'=>'Image','args'=>['dir', 'width', 'height', 'cats', false]],
        'image'=>['desc'=>'Image','args'=>['dir', 'width', 'height', 'cats', true, false]],
        'image'=>['desc'=>'Image','args'=>['dir', 'width', 'height', 'cats', true, true, 'Faker']],
        */
        'uuid'=>['desc'=>'Uuid','args'=>[]],
        'ean13'=>['desc'=>'Ean13','args'=>[]],
        'ean8'=>['desc'=>'Ean8','args'=>[]],
        'isbn13'=>['desc'=>'Isbn13','args'=>[]],
        'isbn10'=>['desc'=>'Isbn10','args'=>[]],
        'boolean'=>['desc'=>'Boolean with probability','args'=>['chanceOfGettingTrue' => 50]],
        'md5'=>['desc'=>'Md5','args'=>[]],
        'sha1'=>['desc'=>'Sha1','args'=>[]],
        'sha256'=>['desc'=>'Sha256','args'=>[]],
        'locale'=>['desc'=>'Locale','args'=>[]],
        'countryCode'=>['desc'=>'Country Code','args'=>[]],
        'languageCode'=>['desc'=>'Language Code','args'=>[]],
        'currencyCode'=>['desc'=>'Currency Code','args'=>[]],
        'emoji'=>['desc'=>'Emoji','args'=>[]],
        'biasedNumberBetween'=>['desc'=>'Biased Number Between','args'=>['min' => 10, 'max' => 20, 'function' => 'sqrt']],
        'randomHtml'=>['desc'=>'Random Html','args'=>[2,3]],
    ];
    public $faker;

    public static function getRules() {
        return self::$rules;
    }

    public function __construct(\Faker\Generator $faker) {
        $this->faker = $faker;
    }

    public function normalizeArgs($rule, array $args) {
        $newArgs = [];
        if (isset(self::$rules[$rule])) {
            foreach (self::$rules[$rule]['args'] as $key => $value) {
                $newArgs[$key] = isset($args[$key]) ? $args[$key] : $value;
            }
        }

        return $newArgs;
    }
}
